const iconsName = {
    action: [
        "search",
        "home",
        "account circle",
        "settings",
        "done",
        "info",
        "check circle",
        "delete",
        "shopping cart",
        "visibility",
        "favorite",
        "logout",
        "description",
        "favorite border",
        "lock",
        "schedule",
        "language",
        "face",
        "help outline",
        "manage accounts",
        "fingerprint",
        "filter alt",
        "event",
        "thumb up",
        "verified",
        "dashboard",
        "calendar today",
        "login",
        "list",
        "visibility off",
        "check circle outline",
        "date range",
        "highlight off",
        "help",
        "question answer",
        "article",
        "paid",
        "task alt",
        "lightbulb",
        "shopping bag",
        "open in new",
        "perm identity",
        "trending up",
        "history",
        "credit card",
        "account balance",
        "report problem",
        "delete outline",
        "fact check",
        "assignment",
        "verified user",
        "arrow right alt",
        "star rate",
        "account balance wallet",
        "autorenew",
        "print",
        "work",
        "build",
        "view list",
        "analytics",
        "today",
        "store",
        "delete forever",
        "admin panel settings",
        "savings",
        "room",
        "lock open",
        "code",
        "grade",
        "receipt",
        "update",
        "watch later",
        "add shopping cart",
        "power settings new",
        "contact support",
        "pets",
        "done all",
        "explore",
        "bookmark",
        "bookmark border",
        "note add",
        "reorder",
        "account box",
        "shopping basket",
        "pending actions",
        "payment",
        "drag indicator",
        "launch",
        "supervisor account",
        "touch app",
        "pending",
        "zoom in",
        "thumb up off alt",
        "assessment",
        "done outline",
        "exit to app",
        "open in full",
        "leaderboard",
        "preview",
        "assignment ind",
        "card giftcard",
        "view in ar",
        "work outline",
        "feedback",
        "timeline",
        "published with changes",
        "dns",
        "swap horiz",
        "assignment turned in",
        "sync alt",
        "book",
        "flight takeoff",
        "stars",
        "android",
        "pan tool",
        "label",
        "bug report",
        "accessibility",
        "gavel",
        "contact page",
        "alarm",
        "cached",
        "translate",
        "supervised user circle",
        "space dashboard",
        "get app",
        "extension",
        "minimize",
        "edit calendar",
        "add task",
        "record voice over",
        "accessibility new",
        "flutter dash",
        "trending flat",
        "thumb down",
        "hourglass empty",
        "help center",
        "sticky note 2",
        "rule",
        "support",
        "dashboard customize",
        "source",
        "find in page",
        "view headline",
        "close fullscreen",
        "announcement",
        "settings applications",
        "group work",
        "redeem",
        "loyalty",
        "calendar month",
        "tips and updates",
        "swap vert",
        "compare arrows",
        "restore",
        "sensors",
        "euro symbol",
        "nightlight round",
        "dangerous",
        "grading",
        "privacy tip",
        "subject",
        "track changes",
        "ads click",
        "copyright",
        "https",
        "table view",
        "disabled by default",
        "arrow circle up",
        "bookmarks",
        "api",
        "query builder",
        "toc",
        "book online",
        "build circle",
        "input",
        "perm media",
        "backup",
        "zoom out",
        "3d rotation",
        "settings phone",
        "arrow circle right",
        "perm contact calendar",
        "open with",
        "circle notifications",
        "view module",
        "arrow circle down",
        "swipe",
        "speaker notes",
        "file present",
        "label important",
        "card membership",
        "wysiwyg",
        "perm phone msg",
        "pageview",
        "integration instructions",
        "upgrade",
        "trending down",
        "g translate",
        "change history",
        "class",
        "accessible",
        "offline bolt",
        "production quantity limits",
        "settings accessibility",
        "model training",
        "expand",
        "calendar view month",
        "aspect ratio",
        "donut large",
        "settings backup restore",
        "maximize",
        "segment",
        "schedule send",
        "bookmark add",
        "thumbs up down",
        "thumb down off alt",
        "view column",
        "question mark",
        "rocket launch",
        "alarm on",
        "settings ethernet",
        "view agenda",
        "theaters",
        "invert colors",
        "important devices",
        "unpublished",
        "open in browser",
        "opacity",
        "commute",
        "addchart",
        "youtube searched for",
        "arrow circle left",
        "no accounts",
        "history toggle off",
        "tour",
        "view week",
        "turned in",
        "shop",
        "settings input antenna",
        "system update alt",
        "mark as unread",
        "bookmark added",
        "flight land",
        "hide source",
        "contactless",
        "saved search",
        "plagiarism",
        "search off",
        "not started",
        "assignment late",
        "percent",
        "donut small",
        "highlight alt",
        "view carousel",
        "anchor",
        "mediation",
        "settings input component",
        "turned in not",
        "flaky",
        "settings remote",
        "remove shopping cart",
        "toll",
        "fit screen",
        "all inbox",
        "edit off",
        "view quilt",
        "assignment return",
        "hourglass full",
        "lock clock",
        "settings voice",
        "online prediction",
        "pregnant woman",
        "camera enhance",
        "swap horizontal circle",
        "event seat",
        "next plan",
        "restore from trash",
        "add to drive",
        "view sidebar",
        "markunread mailbox",
        "calendar view week",
        "accessible forward",
        "vertical split",
        "tab",
        "dynamic form",
        "settings power",
        "hotel class",
        "card travel",
        "remove done",
        "request page",
        "try",
        "smart button",
        "view stream",
        "offline pin",
        "calendar view day",
        "rowing",
        "data exploration",
        "outbox",
        "find replace",
        "outlet",
        "compress",
        "chrome reader mode",
        "alarm add",
        "assignment returned",
        "settings brightness",
        "play for work",
        "http",
        "gif",
        "spellcheck",
        "backup table",
        "restore page",
        "credit card off",
        "wifi protected setup",
        "settings overscan",
        "settings input composite",
        "quickreply",
        "token",
        "filter alt off",
        "polymer",
        "view day",
        "comment bank",
        "currency exchange",
        "line weight",
        "swap vertical circle",
        "new label",
        "balance",
        "cancel schedule send",
        "send and archive",
        "batch prediction",
        "generating tokens",
        "outbound",
        "horizontal split",
        "settings bluetooth",
        "picture in picture",
        "shopping cart checkout",
        "code off",
        "bookmark remove",
        "fax",
        "flip to front",
        "shop two",
        "speaker notes off",
        "perm data setting",
        "perm scan wifi",
        "eject",
        "rocket",
        "free cancellation",
        "gif box",
        "settings cell",
        "alarm off",
        "settings input hdmi",
        "switch access shortcut",
        "hourglass disabled",
        "disabled visible",
        "sensors off",
        "app blocking",
        "line style",
        "work off",
        "perm device information",
        "subtitles off",
        "picture in picture alt",
        "lock reset",
        "update disabled",
        "settings input svideo",
        "voice over off",
        "switch access shortcut add",
        "view array",
        "flip to back",
        "density medium",
        "satellite alt",
        "open in new off",
        "all out",
        "view timeline",
        "label off",
        "rounded corner",
        "tab unselected",
        "text rotate vertical",
        "explore off",
        "terminal",
        "private connectivity",
        "text rotation none",
        "shop 2",
        "not accessible",
        "perm camera mic",
        "pin invoke",
        "add card",
        "webhook",
        "123",
        "extension off",
        "html",
        "swipe left",
        "pin end",
        "text rotate up",
        "assured workload",
        "app shortcut",
        "output",
        "text rotation angledown",
        "text rotation down",
        "join full",
        "text rotation angleup",
        "display settings",
        "swipe right",
        "install desktop",
        "javascript",
        "event repeat",
        "swipe up",
        "pan tool alt",
        "abc",
        "join inner",
        "data thresholding",
        "install mobile",
        "density small",
        "swipe down",
        "join left",
        "commit",
        "view kanban",
        "pinch",
        "view cozy",
        "css",
        "swipe vertical",
        "join right",
        "noise control off",
        "swipe right alt",
        "view comfy alt",
        "view compact alt",
        "manage history",
        "swipe down alt",
        "swipe up alt",
        "php",
        "lightbulb circle",
        "swipe left alt",
        "density large",
        "browse gallery",
        "network ping",
        "noise aware",
        "spatial audio off",
        "hls",
        "hls off",
        "spatial tracking",
        "on device training",
        "spatial audio",
    ],
    alert: [
        "warning",
        "warning",
        "error",
        "error outline",
        "warning amber",
        "notification important",
        "add alert",
        "auto delete"
    ],
    meida: [
        "play arrow",
        "play arrow",
        "play circle filled",
        "videocam",
        "mic",
        "play circle",
        "volume up",
        "pause",
        "play circle outline",
        "volume off",
        "replay",
        "skip next",
        "library books",
        "speed",
        "stop",
        "fiber manual record",
        "movie",
        "skip previous",
        "new releases",
        "playlist add",
        "equalizer",
        "loop",
        "fast forward",
        "web",
        "video library",
        "playlist add check",
        "mic off",
        "library add",
        "video call",
        "subscriptions",
        "pause circle",
        "repeat",
        "shuffle",
        "volume mute",
        "stop circle",
        "not interested",
        "mic none",
        "sort by alpha",
        "library music",
        "fast rewind",
        "videocam off",
        "volume down",
        "queue music",
        "pause circle filled",
        "web asset",
        "recent actors",
        "hearing",
        "subtitles",
        "library add check",
        "album",
        "fiber new",
        "pause circle outline",
        "note",
        "av timer",
        "games",
        "radio",
        "playlist play",
        "replay circle filled",
        "branding watermark",
        "queue",
        "forward 10",
        "replay 10",
        "closed caption",
        "video settings",
        "featured play list",
        "control camera",
        "airplay",
        "slow motion video",
        "add to queue",
        "playlist add check circle",
        "hd",
        "repeat one",
        "call to action",
        "snooze",
        "repeat on",
        "high quality",
        "closed caption off",
        "replay 30",
        "featured video",
        "5g",
        "shuffle on",
        "music video",
        "forward 30",
        "replay 5",
        "queue play next",
        "art track",
        "forward 5",
        "hearing disabled",
        "explicit",
        "playlist add circle",
        "4k",
        "playlist remove",
        "fiber smart record",
        "video label",
        "closed caption disabled",
        "repeat one on",
        "remove from queue",
        "surround sound",
        "web asset off",
        "play disabled",
        "interpreter mode",
        "sd",
        "missed video call",
        "video file",
        "10k",
        "audio file",
        "fiber pin",
        "fiber dvr",
        "4k plus",
        "1k",
        "2k",
        "8k",
        "1k plus",
        "9k plus",
        "8k plus",
        "3k",
        "5k",
        "5k plus",
        "6k",
        "3k plus",
        "7k plus",
        "9k",
        "6k plus",
        "7k",
        "2k plus"
    ],
    communication: [
        "email",
        "email",
        "location on",
        "call",
        "phone",
        "business",
        "chat",
        "mail outline",
        "vpn key",
        "list alt",
        "qr code scanner",
        "chat bubble outline",
        "alternate email",
        "forum",
        "chat bubble",
        "textsms",
        "contact mail",
        "qr code 2",
        "person search",
        "qr code",
        "sentiment satisfied alt",
        "message",
        "comment",
        "contacts",
        "app registration",
        "import contacts",
        "contact phone",
        "live help",
        "import export",
        "forward to inbox",
        "rss feed",
        "hourglass bottom",
        "hourglass top",
        "mark email read",
        "key",
        "read more",
        "call end",
        "mark email unread",
        "more time",
        "document scanner",
        "clear all",
        "dialpad",
        "phone enabled",
        "mark chat unread",
        "3p",
        "screen share",
        "cancel presentation",
        "hub",
        "call made",
        "call split",
        "unsubscribe",
        "present to all",
        "add ic call",
        "domain verification",
        "mark chat read",
        "stay current portrait",
        "phonelink ring",
        "call received",
        "phonelink lock",
        "phone disabled",
        "duo",
        "ring volume",
        "phonelink setup",
        "stay primary portrait",
        "location off",
        "swap calls",
        "voicemail",
        "call merge",
        "mobile screen share",
        "phonelink erase",
        "person add disabled",
        "call missed outgoing",
        "cell wifi",
        "domain disabled",
        "speaker phone",
        "co present",
        "stop screen share",
        "desktop access disabled",
        "call missed",
        "print disabled",
        "pause presentation",
        "dialer sip",
        "invert colors off",
        "rtt",
        "spoke",
        "portable wifi off",
        "wifi calling",
        "stay current landscape",
        "comments disabled",
        "sip",
        "nat",
        "stay primary landscape",
        "no sim",
        "cell tower",
        "send time extension",
        "mark unread chat alt",
        "key off",
        "vpn key off"
    ],
    content: [
        "add",
        "add",
        "add circle outline",
        "add circle",
        "content copy",
        "send",
        "clear",
        "mail",
        "save",
        "link",
        "remove",
        "filter list",
        "inventory 2",
        "insights",
        "sort",
        "remove circle outline",
        "inventory",
        "bolt",
        "reply",
        "flag",
        "add box",
        "create",
        "remove circle",
        "push pin",
        "block",
        "calculate",
        "undo",
        "how to reg",
        "content paste",
        "report",
        "file copy",
        "shield",
        "backspace",
        "archive",
        "save alt",
        "policy",
        "tag",
        "change circle",
        "redo",
        "content cut",
        "forward",
        "inbox",
        "outlined flag",
        "drafts",
        "biotech",
        "link off",
        "ballot",
        "stacked bar chart",
        "markunread",
        "delete sweep",
        "report gmailerrorred",
        "square foot",
        "stream",
        "where to vote",
        "add link",
        "copy all",
        "waves",
        "move to inbox",
        "dynamic feed",
        "unarchive",
        "reply all",
        "select all",
        "low priority",
        "text format",
        "weekend",
        "font download",
        "gesture",
        "upcoming",
        "how to vote",
        "attribution",
        "content paste search",
        "next week",
        "save as",
        "content paste off",
        "content paste go",
        "report off",
        "filter list off",
        "flag circle",
        "font download off",
        "deselect"
    ],
    device: [
        "light mode",
        "light mode",
        "restart alt",
        "dark mode",
        "task",
        "password",
        "summarize",
        "sell",
        "signal cellular alt",
        "devices",
        "settings suggest",
        "quiz",
        "widgets",
        "storage",
        "battery full",
        "thermostat",
        "credit score",
        "gps fixed",
        "price check",
        "medication",
        "pin",
        "price change",
        "tungsten",
        "gpp good",
        "battery charging full",
        "fmd good",
        "note alt",
        "reviews",
        "air",
        "graphic eq",
        "bluetooth",
        "dvr",
        "access time",
        "nightlight",
        "sports score",
        "water",
        "share location",
        "gpp maybe",
        "cable",
        "location searching",
        "cameraswitch",
        "shortcut",
        "monitor heart",
        "airplane ticket",
        "device thermostat",
        "monitor weight",
        "wallpaper",
        "signal wifi 4 bar",
        "data usage",
        "radar",
        "battery std",
        "gpp bad",
        "developer mode",
        "bloodtype",
        "wifi tethering",
        "mode night",
        "signal cellular 4 bar",
        "network wifi",
        "flashlight on",
        "splitscreen",
        "fmd bad",
        "airplanemode active",
        "access time filled",
        "battery alert",
        "mobile friendly",
        "send to mobile",
        "sim card download",
        "lens blur",
        "usb",
        "signal wifi statusbar 4 bar",
        "screen search desktop",
        "screen rotation",
        "signal wifi statusbar connected no internet 4",
        "system security update good",
        "gps not fixed",
        "bluetooth connected",
        "remember me",
        "pattern",
        "nfc",
        "battery saver",
        "brightness high",
        "play lesson",
        "mode standby",
        "storm",
        "network cell",
        "screenshot",
        "data saver off",
        "signal wifi 0 bar",
        "brightness medium",
        "brightness low",
        "data saver on",
        "bluetooth searching",
        "ad units",
        "mobiledata off",
        "grid 4x4",
        "bluetooth disabled",
        "security update good",
        "signal wifi off",
        "hdr auto",
        "discount",
        "battery unknown",
        "signal wifi bad",
        "wifi calling 3",
        "settings system daydream",
        "access alarms",
        "aod",
        "signal wifi connected no internet 4",
        "add to home screen",
        "signal cellular 0 bar",
        "flourescent",
        "security update",
        "gps off",
        "flashlight off",
        "4g mobiledata",
        "access alarm",
        "grid 3x3",
        "sd storage",
        "signal wifi statusbar null",
        "wifi lock",
        "reset tv",
        "brightness auto",
        "do not disturb on total silence",
        "signal cellular connected no internet 4 bar",
        "airplanemode inactive",
        "security update warning",
        "nearby error",
        "1x mobiledata",
        "lan",
        "system security update",
        "screen lock portrait",
        "signal cellular connected no internet 0 bar",
        "ssid chart",
        "wifi tethering off",
        "system security update warning",
        "4g plus mobiledata",
        "edgesensor high",
        "signal wifi 4 bar lock",
        "lte mobiledata",
        "bluetooth drive",
        "media bluetooth on",
        "add alarm",
        "signal cellular nodata",
        "signal cellular off",
        "location disabled",
        "punch clock",
        "signal cellular null",
        "mobile off",
        "30fps",
        "screen lock rotation",
        "rsvp",
        "grid goldenratio",
        "edgesensor low",
        "3g mobiledata",
        "lte plus mobiledata",
        "60fps",
        "screen lock landscape",
        "usb off",
        "timer 10 select",
        "medication liquid",
        "g mobiledata",
        "signal cellular no sim",
        "timer 3 select",
        "wifi password",
        "battery 5 bar",
        "h mobiledata",
        "media bluetooth off",
        "battery 6 bar",
        "battery 4 bar",
        "e mobiledata",
        "battery 0 bar",
        "h plus mobiledata",
        "r mobiledata",
        "hdr on select",
        "hdr auto select",
        "nearby off",
        "hdr off select",
        "battery 3 bar",
        "phishing",
        "wifi tethering error",
        "battery 1 bar",
        "wifi find",
        "battery 2 bar",
        "wifi channel",
        "network wifi 3 bar",
        "network wifi 1 bar",
        "wifi 2 bar",
        "network wifi 2 bar",
        "signal cellular alt 2 bar",
        "signal cellular alt 1 bar",
        "wifi 1 bar",
        "devices fold"
    ],
    editor: [
        "attach money",
        "attach money",
        "format list bulleted",
        "mode edit",
        "monetization on",
        "attach file",
        "edit note",
        "post add",
        "bar chart",
        "checklist",
        "drag handle",
        "insert drive file",
        "show chart",
        "format quote",
        "format list numbered",
        "border color",
        "table chart",
        "pie chart",
        "notes",
        "insert photo",
        "format bold",
        "text fields",
        "insert emoticon",
        "table rows",
        "title",
        "auto graph",
        "publish",
        "mode",
        "insert chart outlined",
        "mode comment",
        "checklist rtl",
        "query stats",
        "insert invitation",
        "mode edit outline",
        "functions",
        "insert link",
        "format italic",
        "format align left",
        "format color fill",
        "horizontal rule",
        "add comment",
        "insert chart",
        "linear scale",
        "draw",
        "format size",
        "format underlined",
        "bubble chart",
        "stacked line chart",
        "money off",
        "insert comment",
        "vertical align bottom",
        "vertical align top",
        "height",
        "format align center",
        "format paint",
        "format color text",
        "format align right",
        "area chart",
        "scatter plot",
        "format list numbered rtl",
        "merge type",
        "highlight",
        "schema",
        "format align justify",
        "add chart",
        "format shapes",
        "money off csred",
        "pie chart outline",
        "short text",
        "square",
        "format indent increase",
        "strikethrough s",
        "numbers",
        "align horizontal left",
        "vertical align center",
        "format color reset",
        "multiline chart",
        "score",
        "border all",
        "data object",
        "format indent decrease",
        "format line spacing",
        "format clear",
        "space bar",
        "align vertical bottom",
        "horizontal distribute",
        "align horizontal center",
        "format strikethrough",
        "align horizontal right",
        "vertical distribute",
        "superscript",
        "margin",
        "hexagon",
        "wrap text",
        "subscript",
        "rectangle",
        "border clear",
        "align vertical top",
        "align vertical center",
        "candlestick chart",
        "border style",
        "move up",
        "padding",
        "border outer",
        "data array",
        "move down",
        "text increase",
        "polyline",
        "pentagon",
        "line axis",
        "border left",
        "border bottom",
        "border inner",
        "format textdirection l to r",
        "border horizontal",
        "border vertical",
        "format textdirection r to l",
        "border top",
        "border right",
        "insert page break",
        "text decrease"
    ],
    file: [
        "file download",
        "file download",
        "file upload",
        "download",
        "folder",
        "grid view",
        "upload file",
        "cloud upload",
        "folder open",
        "text snippet",
        "cloud",
        "request quote",
        "cloud download",
        "drive file rename outline",
        "upload",
        "attachment",
        "download for offline",
        "create new folder",
        "downloading",
        "folder shared",
        "cloud done",
        "topic",
        "download done",
        "cloud queue",
        "approval",
        "cloud off",
        "drive file move",
        "newspaper",
        "workspaces",
        "drive folder upload",
        "file download done",
        "attach email",
        "rule folder",
        "file open",
        "cloud circle",
        "snippet folder",
        "file download off",
        "cloud sync",
        "folder zip",
        "drive file move rtl",
        "folder copy",
        "folder delete",
        "difference",
        "folder off",
        "format overline"
    ],
    hardware: [
        "keyboard arrow down",
        "keyboard arrow down",
        "phone iphone",
        "smartphone",
        "keyboard arrow right",
        "computer",
        "security",
        "smart display",
        "desktop windows",
        "phone android",
        "keyboard backspace",
        "keyboard arrow up",
        "laptop",
        "keyboard arrow left",
        "smart toy",
        "headphones",
        "keyboard",
        "keyboard return",
        "memory",
        "tv",
        "headset mic",
        "point of sale",
        "keyboard double arrow right",
        "mouse",
        "keyboard voice",
        "developer board",
        "videogame asset",
        "router",
        "keyboard double arrow left",
        "keyboard double arrow down",
        "device hub",
        "cast for education",
        "headset",
        "laptop mac",
        "cast",
        "watch",
        "tablet mac",
        "devices other",
        "keyboard double arrow up",
        "keyboard tab",
        "desktop mac",
        "laptop chromebook",
        "phonelink",
        "monitor",
        "speaker",
        "toys",
        "gamepad",
        "keyboard alt",
        "start",
        "sim card",
        "connected tv",
        "tablet android",
        "cast connected",
        "laptop windows",
        "device unknown",
        "keyboard hide",
        "scanner",
        "tablet",
        "browser updated",
        "keyboard capslock",
        "speaker group",
        "earbuds",
        "headset off",
        "home max",
        "headphones battery",
        "smart screen",
        "power input",
        "dock",
        "browser not supported",
        "home mini",
        "earbuds battery",
        "phonelink off",
        "developer board off",
        "videogame asset off",
        "keyboard command key",
        "adf scanner",
        "keyboard control key",
        "keyboard option key",
        "watch off"
    ],
    home: [
        "sensor door",
        "sensor door",
        "sensor window",
        "shield moon"
    ],
    image: [
        "edit",
        "edit",
        "navigate next",
        "photo camera",
        "image",
        "tune",
        "picture as pdf",
        "circle",
        "receipt long",
        "timer",
        "auto stories",
        "navigate before",
        "collections",
        "add a photo",
        "auto awesome",
        "palette",
        "remove red eye",
        "music note",
        "wb sunny",
        "add photo alternate",
        "brush",
        "flash on",
        "euro",
        "auto fix high",
        "control point",
        "adjust",
        "looks one",
        "style",
        "camera",
        "straighten",
        "camera alt",
        "photo library",
        "audiotrack",
        "portrait",
        "video camera front",
        "rotate right",
        "grid on",
        "color lens",
        "crop free",
        "timelapse",
        "landscape",
        "crop square",
        "collections bookmark",
        "slideshow",
        "lens",
        "looks two",
        "panorama fish eye",
        "filter drama",
        "filter vintage",
        "auto awesome motion",
        "compare",
        "healing",
        "image search",
        "rotate left",
        "crop",
        "wb incandescent",
        "looks 3",
        "blur on",
        "center focus strong",
        "wb cloudy",
        "flare",
        "face retouching natural",
        "auto awesome mosaic",
        "dehaze",
        "brightness 4",
        "filter none",
        "colorize",
        "cases",
        "assistant",
        "filter center focus",
        "broken image",
        "nature people",
        "photo",
        "flash off",
        "crop original",
        "currency rupee",
        "details",
        "brightness 5",
        "tag faces",
        "brightness 6",
        "flip camera android",
        "grain",
        "flip",
        "loupe",
        "flip camera ios",
        "brightness 1",
        "movie creation",
        "image not supported",
        "filter 1",
        "panorama",
        "add to photos",
        "center focus weak",
        "animation",
        "auto fix normal",
        "movie filter",
        "view comfy",
        "filter",
        "control point duplicate",
        "crop din",
        "nature",
        "leak add",
        "looks 4",
        "brightness 7",
        "video camera back",
        "photo size select actual",
        "texture",
        "timer off",
        "transform",
        "photo camera front",
        "incomplete circle",
        "view compact",
        "motion photos on",
        "rotate 90 degrees ccw",
        "bedtime",
        "mic external on",
        "gradient",
        "looks 5",
        "music off",
        "assistant photo",
        "thermostat auto",
        "photo album",
        "hdr strong",
        "exposure plus 1",
        "shutter speed",
        "exposure",
        "filter tilt shift",
        "hide image",
        "filter 2",
        "looks",
        "crop 16 9",
        "vrpano",
        "blur circular",
        "linked camera",
        "flash auto",
        "brightness 3",
        "motion photos auto",
        "tonality",
        "wb twilight",
        "looks 6",
        "brightness 2",
        "iso",
        "photo size select small",
        "crop 7 5",
        "photo filter",
        "crop portrait",
        "crop rotate",
        "filter hdr",
        "hdr weak",
        "photo size select large",
        "filter 3",
        "camera front",
        "crop 5 4",
        "exposure zero",
        "filter frames",
        "camera roll",
        "filter b and w",
        "burst mode",
        "rotate 90 degrees cw",
        "blur linear",
        "crop 3 2",
        "contrast",
        "crop landscape",
        "switch camera",
        "switch video",
        "currency bitcoin",
        "filter 7",
        "wb iridescent",
        "currency pound",
        "motion photos paused",
        "filter 9 plus",
        "exposure plus 2",
        "filter 4",
        "grid off",
        "monochrome photos",
        "photo camera back",
        "logo dev",
        "filter 5",
        "face retouching off",
        "auto fix off",
        "currency yen",
        "leak remove",
        "exposure neg 1",
        "panorama photosphere",
        "timer 10",
        "wb shade",
        "filter 9",
        "video stable",
        "filter 8",
        "blur off",
        "motion photos off",
        "hdr on",
        "filter 6",
        "panorama horizontal",
        "raw on",
        "vignette",
        "image aspect ratio",
        "camera rear",
        "dirty lens",
        "timer 3",
        "30fps select",
        "currency ruble",
        "60fps select",
        "24mp",
        "motion photos pause",
        "panorama wide angle select",
        "exposure neg 2",
        "autofps select",
        "panorama horizontal select",
        "panorama photosphere select",
        "panorama wide angle",
        "mic external off",
        "wb auto",
        "hdr plus",
        "panorama vertical select",
        "panorama vertical",
        "hdr enhanced select",
        "12mp",
        "hevc",
        "mp",
        "23mp",
        "raw off",
        "18mp",
        "hdr off",
        "11mp",
        "3mp",
        "10mp",
        "20mp",
        "17mp",
        "21mp",
        "13mp",
        "2mp",
        "16mp",
        "14mp",
        "15mp",
        "22mp",
        "4mp",
        "5mp",
        "19mp",
        "8mp",
        "9mp",
        "7mp",
        "6mp",
        "deblur",
        "currency lira",
        "currency yuan",
        "currency franc",
        "bedtime off"
    ],
    maps: [
        "local shipping",
        "local shipping",
        "place",
        "menu book",
        "local offer",
        "map",
        "badge",
        "category",
        "restaurant",
        "directions car",
        "volunteer activism",
        "local fire department",
        "my location",
        "local mall",
        "flight",
        "near me",
        "handyman",
        "directions run",
        "restaurant menu",
        "layers",
        "medical services",
        "lunch dining",
        "park",
        "local hospital",
        "directions walk",
        "celebration",
        "pin drop",
        "local library",
        "local atm",
        "local activity",
        "local cafe",
        "delivery dining",
        "rate review",
        "person pin",
        "design services",
        "directions bike",
        "fastfood",
        "directions bus",
        "local police",
        "directions car filled",
        "local phone",
        "miscellaneous services",
        "home repair service",
        "local grocery store",
        "zoom out map",
        "hotel",
        "cleaning services",
        "person pin circle",
        "navigation",
        "directions",
        "local gas station",
        "local florist",
        "local parking",
        "money",
        "train",
        "local post office",
        "two wheeler",
        "alt route",
        "traffic",
        "electrical services",
        "local bar",
        "pedal bike",
        "directions boat",
        "agriculture",
        "360",
        "beenhere",
        "liquor",
        "add business",
        "moving",
        "local airport",
        "add location alt",
        "sailing",
        "maps ugc",
        "local dining",
        "ramen dining",
        "local taxi",
        "diamond",
        "hail",
        "local drink",
        "local printshop",
        "route",
        "local pizza",
        "trip origin",
        "theater comedy",
        "not listed location",
        "local laundry service",
        "add location",
        "dinner dining",
        "bakery dining",
        "directions bus filled",
        "transfer within a station",
        "multiple stop",
        "takeout dining",
        "wine bar",
        "terrain",
        "icecream",
        "local pharmacy",
        "store mall directory",
        "museum",
        "nightlife",
        "emergency",
        "add road",
        "set meal",
        "local see",
        "departure board",
        "hardware",
        "electric car",
        "festival",
        "ev station",
        "plumbing",
        "edit location",
        "car rental",
        "attractions",
        "layers clear",
        "local convenience store",
        "edit road",
        "factory",
        "run circle",
        "pest control",
        "dry cleaning",
        "warehouse",
        "moped",
        "edit location alt",
        "edit attributes",
        "wrong location",
        "car repair",
        "satellite",
        "local movies",
        "directions boat filled",
        "taxi alert",
        "breakfast dining",
        "tram",
        "atm",
        "church",
        "transit enterexit",
        "brunch dining",
        "subway",
        "hvac",
        "electric bike",
        "electric scooter",
        "forest",
        "directions transit",
        "bus alert",
        "local car wash",
        "zoom in map",
        "soup kitchen",
        "streetview",
        "local hotel",
        "compass calibration",
        "directions subway",
        "castle",
        "mode of travel",
        "directions railway",
        "electric moped",
        "no meals",
        "electric rickshaw",
        "railway alert",
        "egg",
        "local play",
        "bike scooter",
        "mosque",
        "connecting airports",
        "near me disabled",
        "snowmobile",
        "pest control rodent",
        "directions transit filled",
        "airline stops",
        "no transfer",
        "signpost",
        "merge",
        "directions railway filled",
        "directions subway filled",
        "temple buddhist",
        "airlines",
        "egg alt",
        "flight class",
        "temple hindu",
        "stadium",
        "fort",
        "medical information",
        "kebab dining",
        "synagogue",
        "turn right",
        "fork right",
        "u turn left",
        "straight",
        "car crash",
        "turn left",
        "u turn right",
        "tire repair",
        "crisis alert",
        "roundabout right",
        "turn slight left",
        "turn sharp right",
        "safety check",
        "turn slight right",
        "fork left",
        "roundabout left",
        "turn sharp left",
        "sos",
        "emergency share",
        "ramp left",
        "ramp right",
        "remove road",
        "minor crash",
        "screen rotation alt",
        "emergency recording",
        "no crash"
    ],
    navigation: [
        "close",
        "close",
        "menu",
        "expand more",
        "arrow back",
        "chevron right",
        "arrow forward ios",
        "arrow back ios",
        "arrow drop down",
        "cancel",
        "more vert",
        "chevron left",
        "arrow forward",
        "check",
        "expand less",
        "more horiz",
        "refresh",
        "apps",
        "payments",
        "arrow upward",
        "east",
        "campaign",
        "arrow back ios new",
        "arrow downward",
        "arrow right",
        "menu open",
        "fullscreen",
        "double arrow",
        "unfold more",
        "maps home work",
        "arrow drop up",
        "west",
        "arrow left",
        "south",
        "home work",
        "north",
        "north east",
        "first page",
        "fullscreen exit",
        "arrow drop down circle",
        "expand circle down",
        "last page",
        "unfold less",
        "subdirectory arrow right",
        "legend toggle",
        "south east",
        "app settings alt",
        "assistant direction",
        "subdirectory arrow left",
        "north west",
        "waterfall chart",
        "switch left",
        "south west",
        "switch right",
        "pivot table chart",
        "apps outage",
        "offline share"
    ],
    notification: [
        "support agent",
        "support agent",
        "wifi",
        "account tree",
        "sync",
        "event available",
        "priority high",
        "phone in talk",
        "event note",
        "confirmation number",
        "sms",
        "live tv",
        "ondemand video",
        "wifi off",
        "event busy",
        "drive eta",
        "wc",
        "do not disturb on",
        "more",
        "power",
        "do not disturb",
        "sync problem",
        "time to leave",
        "vpn lock",
        "do disturb on",
        "enhanced encryption",
        "folder special",
        "running with errors",
        "network check",
        "sms failed",
        "do disturb",
        "phone callback",
        "system update",
        "adb",
        "power off",
        "personal video",
        "phone forwarded",
        "voice chat",
        "airline seat recline normal",
        "vibration",
        "do disturb alt",
        "do not disturb alt",
        "sync disabled",
        "tap and play",
        "no encryption",
        "sd card",
        "phone missed",
        "airline seat recline extra",
        "imagesearch roller",
        "mms",
        "disc full",
        "bluetooth audio",
        "no encryption gmailerrorred",
        "sd card alert",
        "airline seat individual suite",
        "sim card alert",
        "do not disturb off",
        "phone paused",
        "phone locked",
        "do disturb off",
        "airline seat flat",
        "network locked",
        "phone bluetooth speaker",
        "airline seat flat angled",
        "tv off",
        "directions off",
        "airline seat legroom normal",
        "airline seat legroom extra",
        "airline seat legroom reduced",
        "sync lock"
    ],
    places: [
        "storefront",
        "storefront",
        "apartment",
        "fitness center",
        "business center",
        "spa",
        "house",
        "meeting room",
        "corporate fare",
        "ac unit",
        "cottage",
        "family restroom",
        "other houses",
        "checkroom",
        "grass",
        "all inclusive",
        "airport shuttle",
        "child care",
        "beach access",
        "pool",
        "kitchen",
        "holiday village",
        "casino",
        "roofing",
        "room service",
        "room preferences",
        "sports bar",
        "free breakfast",
        "bathtub",
        "escalator warning",
        "child friendly",
        "food bank",
        "villa",
        "gite",
        "foundation",
        "night shelter",
        "golf course",
        "microwave",
        "stairs",
        "no photography",
        "backpack",
        "wash",
        "house siding",
        "elevator",
        "cabin",
        "smoking rooms",
        "hot tub",
        "countertops",
        "water damage",
        "fire extinguisher",
        "charging station",
        "soap",
        "rv hookup",
        "carpenter",
        "baby changing station",
        "umbrella",
        "smoke free",
        "rice bowl",
        "tapas",
        "balcony",
        "do not touch",
        "no food",
        "fence",
        "bungalow",
        "wheelchair pickup",
        "houseboat",
        "tty",
        "iron",
        "bento",
        "chalet",
        "crib",
        "dry",
        "no meeting room",
        "escalator",
        "do not step",
        "stroller",
        "no drinks",
        "no cell",
        "no flash",
        "no backpack",
        "no stroller",
        "vaping rooms",
        "vape free"
    ],
    search: [
        "feed",
        "feed",
        "manage search",
        "chair",
        "bed",
        "podcasts",
        "shower",
        "yard",
        "coffee",
        "window",
        "door front",
        "light",
        "garage",
        "dining",
        "flatware",
        "coffee maker",
        "blender",
        "camera indoor",
        "bedroom parent",
        "bathroom",
        "bedroom baby",
        "chair alt",
        "living",
        "door back",
        "door sliding",
        "camera outdoor",
        "doorbell",
        "table restaurant",
        "bedroom child",
        "table bar"
    ],
    social: [
        "person",
        "person",
        "notifications",
        "groups",
        "people",
        "share",
        "person outline",
        "school",
        "person add",
        "public",
        "emoji events",
        "group",
        "notifications active",
        "engineering",
        "construction",
        "people alt",
        "whatsapp",
        "group add",
        "psychology",
        "health and safety",
        "travel explore",
        "emoji emotions",
        "notifications none",
        "sports esports",
        "water drop",
        "thumb up alt",
        "sentiment satisfied",
        "location city",
        "ios share",
        "emoji objects",
        "person add alt",
        "precision manufacturing",
        "sentiment very satisfied",
        "military tech",
        "science",
        "history edu",
        "cake",
        "sentiment dissatisfied",
        "coronavirus",
        "emoji people",
        "sentiment very dissatisfied",
        "self improvement",
        "person remove",
        "poll",
        "sports soccer",
        "female",
        "domain",
        "whatshot",
        "people outline",
        "recommend",
        "mood",
        "male",
        "person off",
        "masks",
        "workspace premium",
        "sentiment neutral",
        "connect without contact",
        "back hand",
        "architecture",
        "person add alt 1",
        "hiking",
        "recycling",
        "notifications off",
        "waving hand",
        "luggage",
        "thumb down alt",
        "mood bad",
        "front hand",
        "emoji nature",
        "catching pokemon",
        "switch account",
        "nights stay",
        "king bed",
        "emoji symbols",
        "sports basketball",
        "handshake",
        "notification add",
        "sports",
        "sports kabaddi",
        "vaccines",
        "reduce capacity",
        "emoji food beverage",
        "sick",
        "interests",
        "emoji transportation",
        "transgender",
        "sports tennis",
        "social distance",
        "real estate agent",
        "deck",
        "elderly",
        "outdoor grill",
        "clean hands",
        "follow the signs",
        "add moderator",
        "piano",
        "sanitizer",
        "plus one",
        "fireplace",
        "cookie",
        "surfing",
        "sports motorsports",
        "sports handball",
        "add reaction",
        "edit notifications",
        "sports baseball",
        "cruelty free",
        "man",
        "heart broken",
        "pages",
        "woman",
        "sports volleyball",
        "sports football",
        "downhill skiing",
        "kayaking",
        "skateboarding",
        "public off",
        "single bed",
        "personal injury",
        "pix",
        "compost",
        "notifications paused",
        "safety divider",
        "remove moderator",
        "hive",
        "person remove alt 1",
        "nordic walking",
        "sports cricket",
        "6 ft apart",
        "sports mma",
        "group remove",
        "co2",
        "paragliding",
        "sports golf",
        "group off",
        "snowboarding",
        "party mode",
        "kitesurfing",
        "fitbit",
        "snowshoeing",
        "ice skating",
        "sports rugby",
        "sports hockey",
        "scale",
        "sledding",
        "sports martial arts",
        "south america",
        "boy",
        "domain add",
        "girl",
        "no luggage",
        "piano off",
        "elderly woman",
        "sports gymnastics",
        "scoreboard",
        "scuba diving",
        "thunderstorm",
        "roller skating",
        "cyclone",
        "sign language",
        "flood",
        "tsunami",
        "severe cold",
        "landslide",
        "volcano"
    ],
    toggle: [
        "star",
        "star",
        "check box",
        "check box outline blank",
        "radio button unchecked",
        "radio button checked",
        "star border",
        "toggle on",
        "star outline",
        "toggle off",
        "star half",
        "indeterminate check box",
        "star purple500",
        "star border purple500"
    ]
}